apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: 520812544446.dkr.ecr.ap-southeast-1.amazonaws.com/lehai-react-app:v1.0.4
        imagePullPolicy: Always
        name: backend
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "0.2"
            memory: "0.5G"
          limits:
            cpu: "0.5"
            memory: "2G"
