apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-v3
  name: frontend-v3
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-v3
  template:
    metadata:
      labels:
        app: frontend-v3
    spec:
      containers:
      - image: 520812544446.dkr.ecr.ap-southeast-1.amazonaws.com/lehai-react-app:v0.0.3
        imagePullPolicy: Always
        name: frontend
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "0.2"
            memory: "0.5G"
          limits:
            cpu: "2.0"
            memory: "2G"
